FROM ams21/cmake:latest as builder

RUN apk update && \
    apk add git \
        ncurses \
        ncurses-dev

WORKDIR /home/

COPY . /home/

WORKDIR /home/build/

RUN ./build

# RUNNER:

FROM alpine:latest as runner

RUN apk update && \
    apk add ncurses libstdc++ libgcc musl libjpeg-turbo ffmpeg

WORKDIR /home/

COPY --from=builder /home/build/main /home/

COPY ./jp2a/src/jp2a /usr/local/bin

COPY ./build/storage /home/storage

#COPY Rick.mp4 /home/

CMD ["/home/main"]

# Requird packages:
#   ncurses
#   libstdc++6
#   libgcc
#   musl
#   libjpeg-turbo
